# Generated by Django 4.2.7 on 2024-12-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_fix_recording_paths'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dtmfsequence',
            options={'ordering': ['level', 'id']},
        ),
        migrations.RenameField(
            model_name='callrecord',
            old_name='transcript',
            new_name='transcription',
        ),
        migrations.RenameField(
            model_name='dtmfsequence',
            old_name='result',
            new_name='description',
        ),
        migrations.AddField(
            model_name='dtmfsequence',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='dtmf_sequence',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='recording_file',
            field=models.CharField(help_text='Имя файла записи', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='dtmfsequence',
            unique_together={('phone_number', 'sequence')},
        ),
        migrations.RemoveField(
            model_name='dtmfsequence',
            name='created_at',
        ),
    ]
