# Generated by Django 4.2.7 on 2024-12-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_alter_dtmfsequence_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtmfsequence',
            name='is_submenu',
            field=models.BooleanField(default=False),
        ),
    ]
